### ISSUE TITLE
Reload crontab from file

### ISSUE THREAD

**Issue by Harvie** [mongoose-os-libs/crontab#1]
Hello. I have implemented logic to update crontab.json in my device and now i want to reload it (same way you would do on Linux server), but i've found this is currently not possible using existing API and crontab items have to be added one by one right now.

Would you please mind adding some call to reload the crontab from fs? (Remove all old crontab entries from cron and parse/add crontab.json entries again)

Thank you.

**Comment by rojer** [comment]
i don't mind, but no promises on ETA

**Comment by Harvie** [comment]
Seems to me like all we need to do is exporting `apply_crontab_from_json()` in header file... And possibly adding function to delete all items currently loaded in cron. Doesn't seem so hard... Do you have any additional tips/ideas? Can i make a pull request?

**Comment by Harvie** [comment]
I've made the needed changes, can you please merge the pull request?

**Comment by rojer** [comment]
reviewed. thanks for doing this and sharing!

**Comment by Harvie** [comment]
Thanks. Can you please update tags?

**Comment by rojer** [comment]
we only add tags on releases, so next tag will be 2.17

**Comment by rojer** [comment]
for now you can specify explicit hash to use for this library, i.e.

```
- origin: https://github.com/mongoose-os-libs/crontab
  version: c53af5b6d624326c3b7e5639a4e9d268d79e246d
```

**Comment by Harvie** [comment]
what about "latest" tag? or can i just use `version: master` ?

**Comment by rojer** [comment]
actually, latest tag on this lib is unnecessary and is a mistake.
latest tag only needed on binary-only libraries.
"latest" in mos terminology gets translated to "master" git branch.

**Comment by Harvie** [comment]
So `version: master` and `version: latest` in mos.yml will both work?

**Comment by rojer** [comment]
`version: master` is what you want in the lib entry.

**Comment by Harvie** [comment]
It seems to me that you've accidentaly reverted my changes through whatever cessantabot is:
https://github.com/mongoose-os-libs/crontab/commit/c3beca77bcf179a72d848b70ccbd398a16228370

**Comment by rojer** [comment]
sorry, that was automated publishing. i'll fix it.

**Comment by rojer** [comment]
reverted and disabled publishing of this repo.

**Comment by Harvie** [comment]
Thanks :)
